modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"

[[mods]]
    modId = "nixstats"
    version = "${version}"
    displayName = "nixStats"
    description = "Configurable stat sidebar HUD. Track phantom timer, blocks mined, entities killed, and any other Minecraft statistic."

[[dependencies.nixstats]]
    modId = "neoforge"
    type = "required"
    versionRange = "[21.9,21.11)"
    ordering = "NONE"
    side = "CLIENT"

[[dependencies.nixstats]]
    modId = "minecraft"
    type = "required"
    versionRange = "[1.21.9,1.21.11)"
    ordering = "NONE"
    side = "CLIENT"
